### ISSUE TITLE
Refactor create_goal.dart and other similar pages

### ISSUE THREAD

**Issue by jakkusu1** [Planma2024/planma-app#102]
Move the widgets (especially the showDurationPicker) to another file because mahimo jud ni ug 600+ lines ang kani na file HAHAHAHAH

![image](https://github.com/user-attachments/assets/51d8b558-6de6-46a9-bfd5-cbbb2c011905)

**Comment by jakkusu1** [comment]
Although if I check to nimo akoang gipang add sa other files, for sure makabantay ka ug gabalik2 na functions. Kato na said functions kay ako raman japon to i refactor oy aron dili mulapas ug around 300 lines ang per file.

**Comment by IJLadera** [comment]
done

**Comment by jakkusu1** [comment]
Aight seems good
