### ISSUE TITLE
Flex issue for "Create Account" button

### ISSUE THREAD

**Issue by jakkusu1** [Planma2024/planma-app#105]
Unwanted flex behavior of text inside the "Create Account" button. See images below:

1. If screen has a width of 396 or wider:
![image](https://github.com/user-attachments/assets/22ba1c28-867f-4c10-bd4f-7a5f80ccd944)

2. If screen has a width of 394 or lower:
![image](https://github.com/user-attachments/assets/6f8a0564-6e9c-4478-a5ab-9bed0bfcf991)

**Comment by IJLadera** [comment]
done

**Comment by jakkusu1** [comment]
Seems good
