### ISSUE TITLE
 Fix Reminder Offset Time Screen UI

### ISSUE THREAD

**Issue by jakkusu1** [Planma2024/planma-app#106]
![image](https://github.com/user-attachments/assets/8b25cac4-40fe-4341-bfa7-c06f04e9d91b)

Fix UI (Appbar, dropdown, etc.)

**Comment by IJLadera** [comment]
done

**Comment by jakkusu1** [comment]
Remove lang guro ang text sa appbar pero i remain ang back button for Reminder Offset Screen.

Additionally, murag wala kaayo na center ang content both sa SleepWake Screen ug Reminder Offset screens.

![image](https://github.com/user-attachments/assets/7df93d83-ae48-47ed-86c5-127ed8ffdf9b)
![image](https://github.com/user-attachments/assets/4aa67383-86bb-4b25-bcd3-b88e978e8745)

**Comment by IJLadera** [comment]
![image](https://github.com/user-attachments/assets/5cb8932c-2e22-4242-a425-df9c0bd019a1)
naka center na sya tho kanang mainAxisalignment

**Comment by IJLadera** [comment]
done
