### ISSUE TITLE
Disable "Set Duration" button from Create/Edit Goal

### ISSUE THREAD

**Issue by jakkusu1** [Planma2024/planma-app#98]
For validation, disable the "Set Duration" button if the duration is 0 hours, 0 minutes, and 0 seconds.

Additionally:
1. Pwede i remove and seconds na field since it doesn't really matter/useless na siya sa context diri.
2. Pwede "00" or "30" lang ang value sa minutes since dili man maka support ang time blocking to display something like a "5 mins" na schedule entry
![image](https://github.com/user-attachments/assets/fe73ece8-251a-41c8-8b23-ea13915a47f4)

**Comment by IJLadera** [comment]
done

**Comment by jakkusu1** [comment]
Maybe change nalang ang display text after selecting na instead of "04:30:00", dapat something like "4 hours and 30 minutes" or "4.5 hours". If achieved, then goods nani siya na issue.

**Comment by IJLadera** [comment]
done

**Comment by jakkusu1** [comment]
Aight seems good

**Comment by jakkusu1** [comment]
I want to add three changes: 
- [ ] 1. Change display text from _"x hours to x minutes"_ to _**"x hrs and x mins"**_
- [ ] 2. If 30 mins lang ang gipili, **_"30 mins"_** lang i display rather than _"0 hrs and 30 mins"_
- [ ] 3. If 1 hour lang gipili, change ang display text from _"1 hours"_ to **_"1 hour"_**

**Comment by IJLadera** [comment]
done for this changes

**Comment by jakkusu1** [comment]
Aight seems good
