### ISSUE TITLE
Form Fields Size Inconsistencies

### ISSUE THREAD

**Issue by jakkusu1** [Planma2024/planma-app#99]
Form Fields are inconsistent height-wise. Might say the text fields (katung mga need ug keyboard para mag input) are a bit too thick for a mobile phone size. Although, I'm stuck in deciding if whether or not all the sizes should be the same as: 
1. "Scheduled Date" or "Deadline" under Create Task; or 
2. "Choose a Subject" under Create Task. 

Just try to see what fits.

![image](https://github.com/user-attachments/assets/c8370940-b1f9-4068-a768-c7713c17dc18)
![image](https://github.com/user-attachments/assets/9c6b5e8c-194e-4e1b-b71b-36972d0ef1ad)
![image](https://github.com/user-attachments/assets/70f0b9d5-1eb4-4911-8df5-62953cf573fc)
![image](https://github.com/user-attachments/assets/a297389f-e63d-4355-921f-4e3f05aa6b38)

**Comment by IJLadera** [comment]
done

**Comment by jakkusu1** [comment]
Aight seems good

**Comment by jakkusu1** [comment]
You forgot to include "Add Semester" screen

**Comment by IJLadera** [comment]
done
